DEBUG    tests.moduletest.conftest:conftest.py:25 Loaded .env from C:\Users\E017093\gitRepos\PolarionMock\.env
INFO     tests.session:conftest.py:231 ================================================================================
INFO     tests.session:conftest.py:232 Test Session Started: 20250806_101811
INFO     tests.session:conftest.py:233 Environment: production
INFO     tests.session:conftest.py:234 ================================================================================
DEBUG    tests.session:conftest.py:151 Test environment: production
DEBUG    tests.session:conftest.py:152 Base URL: N/A
INFO     polarion_api.client:client.py:60 Initialized Polarion client for https://polarion-d.claas.local
DEBUG    polarion_api.client:client.py:107 GET https://polarion-d.claas.local/polarion/rest/projects/Python/workitems?page%5Bsize%5D=5
DEBUG    urllib3.connectionpool:connectionpool.py:1049 Starting new HTTPS connection (1): polarion-d.claas.local:443
DEBUG    urllib3.connectionpool:connectionpool.py:544 https://polarion-d.claas.local:443 "GET /polarion/rest/projects/Python/workitems?page%5Bsize%5D=5 HTTP/1.1" 404 139
DEBUG    polarion_api.client:client.py:115 Response status: 404
DEBUG    polarion_api.client:client.py:117 Response body: {"errors":[{"status":"404","title":"Not Found","detail":"The requested resource [/polarion/rest/projects/Python/workitems] is not available"}]}...
DEBUG    tests.session:conftest.py:151 Test environment: production
DEBUG    tests.session:conftest.py:152 Base URL: N/A
INFO     polarion_api.client:client.py:60 Initialized Polarion client for https://polarion-d.claas.local
DEBUG    tests.session:conftest.py:151 Test environment: production
DEBUG    tests.session:conftest.py:152 Base URL: N/A
INFO     polarion_api.client:client.py:60 Initialized Polarion client for https://polarion-d.claas.local
DEBUG    polarion_api.client:client.py:107 GET https://polarion-d.claas.local/polarion/rest/projects/Python/workitems?page%5Bsize%5D=10&include=module&fields%5Bworkitems%5D=id%2Ctitle&fields%5Bdocuments%5D=id%2Ctitle%2Ctype
DEBUG    urllib3.connectionpool:connectionpool.py:1049 Starting new HTTPS connection (1): polarion-d.claas.local:443
DEBUG    urllib3.connectionpool:connectionpool.py:544 https://polarion-d.claas.local:443 "GET /polarion/rest/projects/Python/workitems?page%5Bsize%5D=10&include=module&fields%5Bworkitems%5D=id%2Ctitle&fields%5Bdocuments%5D=id%2Ctitle%2Ctype HTTP/1.1" 404 139
DEBUG    polarion_api.client:client.py:115 Response status: 404
DEBUG    polarion_api.client:client.py:117 Response body: {"errors":[{"status":"404","title":"Not Found","detail":"The requested resource [/polarion/rest/projects/Python/workitems] is not available"}]}...
DEBUG    tests.session:conftest.py:151 Test environment: production
DEBUG    tests.session:conftest.py:152 Base URL: N/A
INFO     polarion_api.client:client.py:60 Initialized Polarion client for https://polarion-d.claas.local
DEBUG    polarion_api.client:client.py:107 GET https://polarion-d.claas.local/polarion/rest/projects/Python/workitems?page%5Bsize%5D=20&include=module&query=HAS_VALUE%3Amodule
DEBUG    urllib3.connectionpool:connectionpool.py:1049 Starting new HTTPS connection (1): polarion-d.claas.local:443
DEBUG    urllib3.connectionpool:connectionpool.py:544 https://polarion-d.claas.local:443 "GET /polarion/rest/projects/Python/workitems?page%5Bsize%5D=20&include=module&query=HAS_VALUE%3Amodule HTTP/1.1" 404 139
DEBUG    polarion_api.client:client.py:115 Response status: 404
DEBUG    polarion_api.client:client.py:117 Response body: {"errors":[{"status":"404","title":"Not Found","detail":"The requested resource [/polarion/rest/projects/Python/workitems] is not available"}]}...
DEBUG    tests.session:conftest.py:151 Test environment: production
DEBUG    tests.session:conftest.py:152 Base URL: N/A
INFO     polarion_api.client:client.py:60 Initialized Polarion client for https://polarion-d.claas.local
DEBUG    polarion_api.client:client.py:107 GET https://polarion-d.claas.local/polarion/rest/projects/Python/workitems?page%5Bsize%5D=50&include=module
DEBUG    urllib3.connectionpool:connectionpool.py:1049 Starting new HTTPS connection (1): polarion-d.claas.local:443
DEBUG    urllib3.connectionpool:connectionpool.py:544 https://polarion-d.claas.local:443 "GET /polarion/rest/projects/Python/workitems?page%5Bsize%5D=50&include=module HTTP/1.1" 404 139
DEBUG    polarion_api.client:client.py:115 Response status: 404
DEBUG    polarion_api.client:client.py:117 Response body: {"errors":[{"status":"404","title":"Not Found","detail":"The requested resource [/polarion/rest/projects/Python/workitems] is not available"}]}...
2025-08-06 10:18:12,809 [INFO] [__main__] Test reports saved to: test_reports\20250806_101810
2025-08-06 10:18:12,809 [INFO] [__main__] Logs saved to: test_reports\20250806_101810/logs/pytest.log
