INFO     tests.session:conftest.py:231 ================================================================================
INFO     tests.session:conftest.py:232 Test Session Started: 20250805_155358
INFO     tests.session:conftest.py:233 Environment: production
INFO     tests.session:conftest.py:234 ================================================================================
DEBUG    tests.session:conftest.py:151 Test environment: production
DEBUG    tests.session:conftest.py:152 Base URL: N/A
INFO     polarion_api.client:client.py:60 Initialized Polarion client for https://polarion-d.claas.local
DEBUG    polarion_api.client:client.py:107 GET https://polarion-d.claas.local/polarion/rest/projects/elibrary/spaces/_default/documents/requirements?include=author%2Cproject
DEBUG    urllib3.connectionpool:connectionpool.py:1049 Starting new HTTPS connection (1): polarion-d.claas.local:443
DEBUG    urllib3.connectionpool:connectionpool.py:544 https://polarion-d.claas.local:443 "GET /polarion/rest/projects/elibrary/spaces/_default/documents/requirements?include=author%2Cproject HTTP/1.1" 404 157
DEBUG    polarion_api.client:client.py:115 Response status: 404
DEBUG    polarion_api.client:client.py:117 Response body: {"errors":[{"status":"404","title":"Not Found","detail":"The requested resource [/polarion/rest/projects/elibrary/spaces/_default/documents/requirements] is not available"}]}...
DEBUG    tests.session:conftest.py:151 Test environment: production
DEBUG    tests.session:conftest.py:152 Base URL: N/A
INFO     polarion_api.client:client.py:60 Initialized Polarion client for https://polarion-d.claas.local
DEBUG    polarion_api.client:client.py:107 GET https://polarion-d.claas.local/polarion/rest/projects/Python/spaces/_default/documents
DEBUG    urllib3.connectionpool:connectionpool.py:1049 Starting new HTTPS connection (1): polarion-d.claas.local:443
DEBUG    urllib3.connectionpool:connectionpool.py:544 https://polarion-d.claas.local:443 "GET /polarion/rest/projects/Python/spaces/_default/documents HTTP/1.1" 404 148
DEBUG    polarion_api.client:client.py:115 Response status: 404
DEBUG    polarion_api.client:client.py:117 Response body: {"errors":[{"status":"404","title":"Not Found","detail":"The requested resource [/polarion/rest/projects/Python/spaces/_default/documents] is not available"}]}...
WARNING  polarion_api.documents:documents.py:81 GET documents in space may not be supported: Unexpected error: [404] _default with ID 'documents' not found
DEBUG    tests.session:conftest.py:151 Test environment: production
DEBUG    tests.session:conftest.py:152 Base URL: N/A
INFO     polarion_api.client:client.py:60 Initialized Polarion client for https://polarion-d.claas.local
INFO     polarion_api.utils:utils.py:301 Saved output to: C:\Users\E017093\gitRepos\PolarionMock\tests\moduletest\..\..\src\polarion_api\test_data\output\20250805_155359_documents_get_myproject__default_mydoc_response.json
DEBUG    tests.session:conftest.py:151 Test environment: production
DEBUG    tests.session:conftest.py:152 Base URL: N/A
INFO     polarion_api.client:client.py:60 Initialized Polarion client for https://polarion-d.claas.local
DEBUG    polarion_api.client:client.py:107 GET https://polarion-d.claas.local/polarion/rest/projects/nonexistent/spaces/_default/documents/FAKE-DOC
DEBUG    urllib3.connectionpool:connectionpool.py:1049 Starting new HTTPS connection (1): polarion-d.claas.local:443
DEBUG    urllib3.connectionpool:connectionpool.py:544 https://polarion-d.claas.local:443 "GET /polarion/rest/projects/nonexistent/spaces/_default/documents/FAKE-DOC HTTP/1.1" 404 162
DEBUG    polarion_api.client:client.py:115 Response status: 404
DEBUG    polarion_api.client:client.py:117 Response body: {"errors":[{"status":"404","title":"Not Found","detail":"The requested resource [/polarion/rest/projects/nonexistent/spaces/_default/documents/FAKE-DOC] is not available"}]}...
2025-08-05 15:54:00,093 [INFO] [__main__] Test reports saved to: test_reports\20250805_155357
2025-08-05 15:54:00,093 [INFO] [__main__] Logs saved to: test_reports\20250805_155357/logs/pytest.log
