DEBUG    tests.moduletest.conftest:conftest.py:25 Loaded .env from C:\Users\E017093\gitRepos\PolarionMock\.env
INFO     tests.session:conftest.py:231 ================================================================================
INFO     tests.session:conftest.py:232 Test Session Started: 20250805_201916
INFO     tests.session:conftest.py:233 Environment: production
INFO     tests.session:conftest.py:234 ================================================================================
DEBUG    tests.session:conftest.py:151 Test environment: production
DEBUG    tests.session:conftest.py:152 Base URL: N/A
INFO     polarion_api.client:client.py:60 Initialized Polarion client for https://polarion-d.claas.local
DEBUG    polarion_api.client:client.py:107 GET https://polarion-d.claas.local/polarion/rest/all/documents
DEBUG    urllib3.connectionpool:connectionpool.py:1049 Starting new HTTPS connection (1): polarion-d.claas.local:443
DEBUG    urllib3.connectionpool:connectionpool.py:544 https://polarion-d.claas.local:443 "GET /polarion/rest/all/documents?query=project.id%3APython&page%5Bsize%5D=100&fields%5Bdocuments%5D=id HTTP/1.1" 404 128
DEBUG    polarion_api.client:client.py:115 Response status: 404
DEBUG    polarion_api.client:client.py:117 Response body: {"errors":[{"status":"404","title":"Not Found","detail":"The requested resource [/polarion/rest/all/documents] is not available"}]}...
DEBUG    polarion_api.documents:documents.py:416 Failed to query documents for spaces: Unexpected error: [404] all with ID 'documents?query=project.id%3APython&page%5Bsize%5D=100&fields%5Bdocuments%5D=id' not found
DEBUG    polarion_api.client:client.py:107 GET https://polarion-d.claas.local/polarion/rest/all/workitems
DEBUG    urllib3.connectionpool:connectionpool.py:544 https://polarion-d.claas.local:443 "GET /polarion/rest/all/workitems?query=project.id%3APython+AND+HAS_VALUE%3AmoduleURI&page%5Bsize%5D=50&fields%5Bworkitems%5D=moduleURI HTTP/1.1" 404 129
DEBUG    polarion_api.client:client.py:115 Response status: 404
DEBUG    polarion_api.client:client.py:117 Response body: {"errors":[{"status":"404","title":"Not Found","detail":"The requested resource [/polarion/rest/all/workitems] is not available"}]}...
DEBUG    polarion_api.documents:documents.py:450 Failed to query work items for spaces: Unexpected error: [404] all with ID 'workitems?query=project.id%3APython+AND+HAS_VALUE%3AmoduleURI&page%5Bsize%5D=50&fields%5Bworkitems%5D=moduleURI' not found
DEBUG    polarion_api.client:client.py:107 HEAD https://polarion-d.claas.local/polarion/rest/projects/Python/spaces/_default/documents
DEBUG    urllib3.connectionpool:connectionpool.py:544 https://polarion-d.claas.local:443 "HEAD /polarion/rest/projects/Python/spaces/_default/documents HTTP/1.1" 404 0
DEBUG    polarion_api.client:client.py:115 Response status: 404
DEBUG    polarion_api.client:client.py:107 HEAD https://polarion-d.claas.local/polarion/rest/projects/Python/spaces/Default/documents
DEBUG    urllib3.connectionpool:connectionpool.py:544 https://polarion-d.claas.local:443 "HEAD /polarion/rest/projects/Python/spaces/Default/documents HTTP/1.1" 404 0
DEBUG    polarion_api.client:client.py:115 Response status: 404
DEBUG    polarion_api.client:client.py:107 HEAD https://polarion-d.claas.local/polarion/rest/projects/Python/spaces/default/documents
DEBUG    urllib3.connectionpool:connectionpool.py:544 https://polarion-d.claas.local:443 "HEAD /polarion/rest/projects/Python/spaces/default/documents HTTP/1.1" 404 0
DEBUG    polarion_api.client:client.py:115 Response status: 404
DEBUG    polarion_api.client:client.py:107 HEAD https://polarion-d.claas.local/polarion/rest/projects/Python/spaces/Requirements/documents
DEBUG    urllib3.connectionpool:connectionpool.py:544 https://polarion-d.claas.local:443 "HEAD /polarion/rest/projects/Python/spaces/Requirements/documents HTTP/1.1" 404 0
DEBUG    polarion_api.client:client.py:115 Response status: 404
DEBUG    polarion_api.client:client.py:107 HEAD https://polarion-d.claas.local/polarion/rest/projects/Python/spaces/TestCases/documents
DEBUG    urllib3.connectionpool:connectionpool.py:544 https://polarion-d.claas.local:443 "HEAD /polarion/rest/projects/Python/spaces/TestCases/documents HTTP/1.1" 404 0
DEBUG    polarion_api.client:client.py:115 Response status: 404
DEBUG    polarion_api.client:client.py:107 HEAD https://polarion-d.claas.local/polarion/rest/projects/Python/spaces/Documents/documents
DEBUG    urllib3.connectionpool:connectionpool.py:544 https://polarion-d.claas.local:443 "HEAD /polarion/rest/projects/Python/spaces/Documents/documents HTTP/1.1" 404 0
DEBUG    polarion_api.client:client.py:115 Response status: 404
DEBUG    polarion_api.client:client.py:107 HEAD https://polarion-d.claas.local/polarion/rest/projects/Python/spaces/Specifications/documents
DEBUG    urllib3.connectionpool:connectionpool.py:544 https://polarion-d.claas.local:443 "HEAD /polarion/rest/projects/Python/spaces/Specifications/documents HTTP/1.1" 404 0
DEBUG    polarion_api.client:client.py:115 Response status: 404
DEBUG    polarion_api.client:client.py:107 HEAD https://polarion-d.claas.local/polarion/rest/projects/Python/spaces/Tests/documents
DEBUG    urllib3.connectionpool:connectionpool.py:544 https://polarion-d.claas.local:443 "HEAD /polarion/rest/projects/Python/spaces/Tests/documents HTTP/1.1" 404 0
DEBUG    polarion_api.client:client.py:115 Response status: 404
DEBUG    polarion_api.client:client.py:107 HEAD https://polarion-d.claas.local/polarion/rest/projects/Python/spaces/Design/documents
DEBUG    urllib3.connectionpool:connectionpool.py:544 https://polarion-d.claas.local:443 "HEAD /polarion/rest/projects/Python/spaces/Design/documents HTTP/1.1" 404 0
DEBUG    polarion_api.client:client.py:115 Response status: 404
DEBUG    polarion_api.client:client.py:107 HEAD https://polarion-d.claas.local/polarion/rest/projects/Python/spaces/Implementation/documents
DEBUG    urllib3.connectionpool:connectionpool.py:544 https://polarion-d.claas.local:443 "HEAD /polarion/rest/projects/Python/spaces/Implementation/documents HTTP/1.1" 404 0
DEBUG    polarion_api.client:client.py:115 Response status: 404
DEBUG    polarion_api.client:client.py:107 HEAD https://polarion-d.claas.local/polarion/rest/projects/Python/spaces/Maintenance/documents
DEBUG    urllib3.connectionpool:connectionpool.py:544 https://polarion-d.claas.local:443 "HEAD /polarion/rest/projects/Python/spaces/Maintenance/documents HTTP/1.1" 404 0
DEBUG    polarion_api.client:client.py:115 Response status: 404
2025-08-05 20:19:17,713 [INFO] [__main__] Test reports saved to: test_reports\20250805_201915
2025-08-05 20:19:17,713 [INFO] [__main__] Logs saved to: test_reports\20250805_201915/logs/pytest.log
